<?php

namespace Database\Seeders;

use App\Models\User;
use App\Models\Product;
use App\Models\Booking;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        // 1. Membuat Akun Admin
        User::updateOrCreate(
            ['email' => 'admin@pbl.com'],
            [
                'name' => 'Admin',
                'password' => Hash::make('123'),
                'role' => 'admin',
            ]
        );

        // 2. Membuat Akun User (Pelanggan)
        User::updateOrCreate(
            ['email' => 'user@pbl.com'],
            [
                'name' => 'Pelanggan Tes',
                'password' => Hash::make('123'),
                'role' => 'user',
            ]
        );

        $products = [
            [
                'name' => 'Honda CR-V',
                'sku' => 'CRV_01',
                'type' => 'SUV',
                'brand' => 'Honda',
                'model' => 'CR-V Turbo',
                'capacity' => 5,
                'transmission' => 'Automatic',
                'fuel_type' => 'Bensin',
                'location' => 'Malang',
                'description' => 'SUV tangguh dengan konsumsi bahan bakar efisien dan interior mewah.',
                'price' => 850000,
                'stock' => 3,
                'is_active' => true,
                'is_booked' => false,
                'is_featured' => false,
            ],
            [
                'name' => 'Daihatsu Xenia',
                'sku' => 'XENIA_01',
                'type' => 'MPV',
                'brand' => 'Daihatsu',
                'model' => 'Xenia 1.3',
                'capacity' => 7,
                'transmission' => 'Manual',
                'fuel_type' => 'Bensin',
                'location' => 'Surabaya',
                'description' => 'Compact MPV yang sangat populer, hemat BBM dan perawatan murah.',
                'price' => 450000,
                'stock' => 4,
                'is_active' => true,
                'is_booked' => false,
                'is_featured' => true,
            ],
            [
                'name' => 'Suzuki Ertiga',
                'sku' => 'ERTIGA_01',
                'type' => 'MPV',
                'brand' => 'Suzuki',
                'model' => 'Ertiga GA',
                'capacity' => 7,
                'transmission' => 'Automatic',
                'fuel_type' => 'Bensin',
                'location' => 'Malang',
                'description' => 'MPV modern dengan kapasitas besar dan teknologi terkini.',
                'price' => 550000,
                'stock' => 3,
                'is_active' => true,
                'is_booked' => false,
                'is_featured' => false,
            ],
            [
                'name' => 'Toyota Innova',
                'sku' => 'INNOVA_01',
                'type' => 'MPV',
                'brand' => 'Toyota',
                'model' => 'Innova 2.4 Diesel',
                'capacity' => 8,
                'transmission' => 'Automatic',
                'fuel_type' => 'Diesel',
                'location' => 'Surabaya',
                'description' => 'Premium MPV dengan mesin diesel yang ekonomis, cocok untuk keluarga besar.',
                'price' => 900000,
                'stock' => 2,
                'is_active' => true,
                'is_booked' => false,
                'is_featured' => true,
            ],
            [
                'name' => 'Mitsubishi Xpander',
                'sku' => 'XPANDER_01',
                'type' => 'MPV',
                'brand' => 'Mitsubishi',
                'model' => 'Xpander 1.5',
                'capacity' => 7,
                'transmission' => 'Manual',
                'fuel_type' => 'Bensin',
                'location' => 'Malang',
                'description' => 'MPV dengan desain sporty dan performance yang responsif.',
                'price' => 600000,
                'stock' => 4,
                'is_active' => true,
                'is_booked' => false,
                'is_featured' => false,
            ],
            [
                'name' => 'Toyota Fortuner',
                'sku' => 'FORTUNER_01',
                'type' => 'SUV',
                'brand' => 'Toyota',
                'model' => 'Fortuner 2.8 Diesel',
                'capacity' => 7,
                'transmission' => 'Automatic',
                'fuel_type' => 'Diesel',
                'location' => 'Surabaya',
                'description' => 'SUV premium dengan performa off-road yang handal dan interior mewah.',
                'price' => 1200000,
                'stock' => 2,
                'is_active' => true,
                'is_booked' => false,
                'is_featured' => true,
            ],
            [
                'name' => 'Honda Brio',
                'sku' => 'BRIO_01',
                'type' => 'Sedan',
                'brand' => 'Honda',
                'model' => 'Brio 1.2',
                'capacity' => 5,
                'transmission' => 'Automatic',
                'fuel_type' => 'Bensin',
                'location' => 'Malang',
                'description' => 'City car yang compact, irit BBM, dan mudah dikendara di jalanan ramai.',
                'price' => 400000,
                'stock' => 5,
                'is_active' => true,
                'is_booked' => false,
                'is_featured' => true,
            ],
            [
                'name' => 'Hyundai Creta',
                'sku' => 'CRETA_01',
                'type' => 'SUV',
                'brand' => 'Hyundai',
                'model' => 'Creta 1.6',
                'capacity' => 5,
                'transmission' => 'Automatic',
                'fuel_type' => 'Bensin',
                'location' => 'Malang',
                'description' => 'SUV compact dengan teknologi canggih dan harga terjangkau.',
                'price' => 700000,
                'stock' => 3,
                'is_active' => true,
                'is_booked' => false,
                'is_featured' => false,
            ],
            [
                'name' => 'Nissan Serena',
                'sku' => 'SERENA_01',
                'type' => 'MPV',
                'brand' => 'Nissan',
                'model' => 'Serena 2.0',
                'capacity' => 7,
                'transmission' => 'Automatic',
                'fuel_type' => 'Bensin',
                'location' => 'Surabaya',
                'description' => 'Premium MPV dengan sliding door, ideal untuk keluarga modern.',
                'price' => 950000,
                'stock' => 2,
                'is_active' => true,
                'is_booked' => false,
                'is_featured' => false,
            ],
            [
                'name' => 'Toyota Avanza',
                'sku' => 'AVANZA_01',
                'type' => 'MPV',
                'brand' => 'Toyota',
                'model' => 'Avanza 1.3',
                'capacity' => 7,
                'transmission' => 'Manual',
                'fuel_type' => 'Bensin',
                'location' => 'Malang',
                'description' => 'Mobil keluarga yang irit dan nyaman untuk perjalanan jarak dekat maupun jauh.',
                'price' => 500000,
                'stock' => 5,
                'is_booked' => false,
                'is_featured' => true,
            ],
        ];

        $carData = [
            'AVANZA_01' => [
                'tahun' => 2023,
                'warna' => 'Putih',
                'plat_nomor' => 'L 5678 BJ',
                'transmisi' => 'Manual',
                'bahan_bakar' => 'Bensin',
                'kapasitas_mesin' => 1300,
                'kapasitas_penumpang' => 7,
                'fitur' => ['AC', 'Power Steering', 'Audio System', 'Rem ABS'],
                'kondisi' => 'Mobil dalam kondisi prima, terawat dengan baik, interior bersih.',
            ],
            'CRV_01' => [
                'tahun' => 2023,
                'warna' => 'Hitam Mutiara',
                'plat_nomor' => 'L 1234 AB',
                'transmisi' => 'Automatic',
                'bahan_bakar' => 'Bensin',
                'kapasitas_mesin' => 1500,
                'kapasitas_penumpang' => 5,
                'fitur' => ['AC', 'Power Steering', 'Audio System Premium', 'GPS Navigation', 'Sunroof', 'Rem ABS', 'Airbag'],
                'kondisi' => 'SUV mewah dalam kondisi sempurna, garansi resmi masih aktif.',
            ],
            'XENIA_01' => [
                'tahun' => 2022,
                'warna' => 'Silver',
                'plat_nomor' => 'L 9876 CD',
                'transmisi' => 'Manual',
                'bahan_bakar' => 'Bensin',
                'kapasitas_mesin' => 1300,
                'kapasitas_penumpang' => 7,
                'fitur' => ['AC', 'Power Steering', 'Audio System', 'Rem ABS'],
                'kondisi' => 'Mobil keluarga terpercaya, hemat BBM, mudah dikendara.',
            ],
            'ERTIGA_01' => [
                'tahun' => 2023,
                'warna' => 'Abu-abu',
                'plat_nomor' => 'L 5432 EF',
                'transmisi' => 'Automatic',
                'bahan_bakar' => 'Bensin',
                'kapasitas_mesin' => 1500,
                'kapasitas_penumpang' => 7,
                'fitur' => ['AC', 'Power Steering', 'Audio System', 'Rem ABS', 'Cruise Control'],
                'kondisi' => 'MPV modern dengan teknologi terkini, interior nyaman.',
            ],
            'INNOVA_01' => [
                'tahun' => 2022,
                'warna' => 'Putih',
                'plat_nomor' => 'L 2345 GH',
                'transmisi' => 'Automatic',
                'bahan_bakar' => 'Diesel',
                'kapasitas_mesin' => 2400,
                'kapasitas_penumpang' => 8,
                'fitur' => ['AC', 'Power Steering', 'Audio System', 'Rem ABS', 'Panoramic Roof', 'Dual Airbag'],
                'kondisi' => 'Premium MPV diesel, ekonomis untuk perjalanan jarak jauh.',
            ],
            'XPANDER_01' => [
                'tahun' => 2023,
                'warna' => 'Merah',
                'plat_nomor' => 'L 3456 IJ',
                'transmisi' => 'Manual',
                'bahan_bakar' => 'Bensin',
                'kapasitas_mesin' => 1500,
                'kapasitas_penumpang' => 7,
                'fitur' => ['AC', 'Power Steering', 'Audio System', 'Rem ABS', 'Spoiler'],
                'kondisi' => 'MPV sporty dengan performa responsif, ideal untuk keluarga muda.',
            ],
            'FORTUNER_01' => [
                'tahun' => 2023,
                'warna' => 'Hitam',
                'plat_nomor' => 'L 4567 KL',
                'transmisi' => 'Automatic',
                'bahan_bakar' => 'Diesel',
                'kapasitas_mesin' => 2800,
                'kapasitas_penumpang' => 7,
                'fitur' => ['AC', 'Power Steering', 'Audio System Premium', 'GPS', '4x4 Mode', 'Cruise Control', 'Airbag'],
                'kondisi' => 'SUV premium dengan performa off-road, interior mewah dan aman.',
            ],
            'BRIO_01' => [
                'tahun' => 2023,
                'warna' => 'Biru',
                'plat_nomor' => 'L 5678 MN',
                'transmisi' => 'Automatic',
                'bahan_bakar' => 'Bensin',
                'kapasitas_mesin' => 1200,
                'kapasitas_penumpang' => 5,
                'fitur' => ['AC', 'Power Steering', 'Audio System', 'Rem ABS'],
                'kondisi' => 'City car kompak, irit BBM, sempurna untuk jalanan kota.',
            ],
            'CRETA_01' => [
                'tahun' => 2023,
                'warna' => 'Coklat',
                'plat_nomor' => 'L 6789 OP',
                'transmisi' => 'Automatic',
                'bahan_bakar' => 'Bensin',
                'kapasitas_mesin' => 1600,
                'kapasitas_penumpang' => 5,
                'fitur' => ['AC', 'Power Steering', 'Audio System', 'Rem ABS', 'Bluetooth', 'Touchscreen'],
                'kondisi' => 'SUV kompak dengan teknologi canggih, harga terjangkau.',
            ],
            'SERENA_01' => [
                'tahun' => 2022,
                'warna' => 'Silver Metallic',
                'plat_nomor' => 'L 7890 QR',
                'transmisi' => 'Automatic',
                'bahan_bakar' => 'Bensin',
                'kapasitas_mesin' => 2000,
                'kapasitas_penumpang' => 7,
                'fitur' => ['AC', 'Power Steering', 'Audio System Premium', 'Sliding Door', 'Cruise Control', 'Airbag'],
                'kondisi' => 'Premium MPV dengan sliding door, ideal untuk keluarga modern.',
            ],
        ];

        foreach ($products as $p) {
            $cData = $carData[$p['sku']] ?? [
                'tahun' => 2023,
                'warna' => 'Putih',
                'plat_nomor' => 'L XXXX XX',
                'kapasitas_mesin' => 1300,
                'fitur' => ['AC', 'Power Steering', 'Audio System'],
                'kondisi' => 'Mobil dalam kondisi baik.',
            ];

            $product = Product::updateOrCreate(['sku' => $p['sku']], array_merge($p, $cData));

            // 3. Data Seed Booking (Relasi ke Product yang baru dibuat)
            Booking::create([
                'product_id' => $product->id,
                'customer_name' => 'Budi Santoso',
                'customer_contact' => '08123456789',
                'start_date' => now()->addDays(1),
                'end_date' => now()->addDays(3),
                'total_price' => $product->price * 2,
                'payment_method' => 'transfer',
                'status' => 'pending',
                'pickup_location' => 'Bandara Abdul Rachman Saleh',
            ]);
        }
    }
}
